export const informationTournaments = [{
    nameTournament: "Iberian Cup 2024",
    team1: "LLT Latin Loler Tean",
    team2: "G2 España",
    date: "12.10.24",
    hour: "18:00",
    match: "Bo1",
    result1: "1",
    result2: "0",

},

    {
        nameTournament: "Iberian Cup 2024",
        team1: "LLT Latin Loler Team",
        team2: "G2 España",
        date: "12.10.24",
        hour: "18:00",
        match: "Bo1",
        result1: "1",
        result2: "0",
    },
    {
        nameTournament: "European Championship 2024",
        team1: "Team A",
        team2: "Team B",
        date: "13.10.24",
        hour: "19:00",
        match: "Bo3",
        result1: "2",
        result2: "1",
    },
    {
        nameTournament: "Global League 2024",
        team1: "Alpha Squad",
        team2: "Beta Crew",
        date: "14.10.24",
        hour: "20:00",
        match: "Bo5",
        result1: "3",
        result2: "2",
    },
    {
        nameTournament: "Iberian Cup 2024",
        team1: "Team C",
        team2: "Team D",
        date: "15.10.24",
        hour: "21:00",
        match: "Bo1",
        result1: "0",
        result2: "1",
    },
    {
        nameTournament: "Champions League 2024",
        team1: "Team E",
        team2: "Team F",
        date: "16.10.24",
        hour: "22:00",
        match: "Bo3",
        result1: "1",
        result2: "3",
    },
    {
        nameTournament: "Iberian Cup 2024",
        team1: "LLT Latin Loler Team",
        team2: "G2 España",
        date: "17.10.24",
        hour: "18:30",
        match: "Bo1",
        result1: "2",
        result2: "2",
    },
    {
        nameTournament: "Summer Tournament 2024",
        team1: "Team G",
        team2: "Team H",
        date: "18.10.24",
        hour: "19:30",
        match: "Bo5",
        result1: "1",
        result2: "4",
    },
    {
        nameTournament: "Winter Championship 2024",
        team1: "Team I",
        team2: "Team J",
        date: "19.10.24",
        hour: "20:30",
        match: "Bo3",
        result1: "0",
        result2: "2",
    },
    {
        nameTournament: "Iberian Cup 2024",
        team1: "Team K",
        team2: "Team L",
        date: "20.10.24",
        hour: "21:30",
        match: "Bo1",
        result1: "1",
        result2: "1",
    },
    {
        nameTournament: "Final Tournament 2024",
        team1: "Team M",
        team2: "Team N",
        date: "21.10.24",
        hour: "22:30",
        match: "Bo5",
        result1: "3",
        result2: "1",
    },
];

